spring.application.name=backend



#Baza
spring.datasource.url=jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:5432}/${SPRING_DATASOURCE_DATABASE:projekt}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

#Ustawienia JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}
tasks.rabbitmq.reply-timeout-ms=${TASKS_RABBITMQ_REPLY_TIMEOUT_MS:10000}
node.monitoring.expected-nodes=${NODE_MONITORING_EXPECTED_NODES:node-1:100,node-2:50,node-3:10}
node.monitoring.ttl-seconds=${NODE_MONITORING_TTL_SECONDS:15}


#JWT

jwt.secret=f1b2a02fc00a55536c7b1495ed87d8e1979b761de7b4e57048000d0b91ed23f786ab23004a6f4ebaba88d22b3faa29ef2d5b3e7a0c8972ea1cff32d8f2efd7d9
jwt.expiration=86400000

#API-DOC
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui-custom.html
springdoc.swagger-ui.operationsSorter=method
